# CoovaChilli-Go Configuration

# General settings
foreground: true
pidfile: /var/run/chilli.pid
interval: 3600s

# TUN/TAP settings
tundev: tun0

# Network settings
net: 10.1.0.0/24
uamlisten: 10.1.0.1
dhcplisten: 10.1.0.1

# DHCP settings
dhcpif: chilli_lan
extif: eth0
clientisolation: true
dhcprelay: false
dhcpupstream: "" # e.g., 192.168.1.1
dhcpstart: 10.1.0.100
dhcpend: 10.1.0.200
dhcpstart_v6: "fd00::100"
dhcpend_v6: "fd00::200"
lease: 1h
dns1: 8.8.8.8
dns2: 8.8.4.4

# RADIUS settings
radiuslisten: 10.1.0.1
radiusserver1: 127.0.0.1
radiusauthport: 1812
radiusacctport: 1813
radiussecret: "secret"
radiusnasid: "coovachilli-go"
coaport: 3799

# UAM/Captive Portal settings
uamport: 8080
certfile: "" # /etc/coovachilli/cert.pem
keyfile: ""  # /etc/coovachilli/key.pem
uamallowed:
  - "www.google.com"
  - "www.google.co.in"
  - "www.github.com"
  - "github.com"
defsessiontimeout: 86400 # 24 hours
defidletimeout: 600     # 10 minutes
defbandwidthmaxdown: 1000000 # 1 Mbps
defbandwidthmaxup: 256000    # 256 Kbps

# Management
cmdsockpath: /var/run/chilli.sock
statefile: /tmp/chilli.state

# Scripts
conup: "coovachilli-go/conup.sh"
condown: "coovachilli-go/condown.sh"
