[package]
name = "chilli-core"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8.5"
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "1", features = ["full", "sync"] }
tracing = "0.1"

[dev-dependencies]
toml = "0.8"
tempfile = "3"
